### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by liangchunn** [WalshyDev/Discord-Spotify-RPC#10]
**Machine details**
`node -v` : `v8.1.1`
`npm -v` : `v5.5.1`
`node -pe "require('process').platform"` : `win32`

**Have I followed the 2 steps:** Yes

**Error shown**
```
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1130:19)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9) code: 'ECONNRESET' }
```

**Comment by liangchunn** [comment]
I seem to have fixed the problem with this. 
Turns out that you need to change `https` to `http` in **line 158** of `node_modules/node-spotify-webhelper/index.js`
