### ISSUE TITLE
SyntaxError?

### ISSUE THREAD

**Issue by trevorkerney** [WalshyDev/Discord-Spotify-RPC#15]
After downloading, and following instructions correctly, this is what I get after doing npm start.

C:\Users\Trevor Kerney\Documents\GitHub\Discord-Spotify-RPC\index.js:14
async function updateActivity() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-spotify-rpc@1.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-spotify-rpc@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Trevor Kerney\AppData\Roaming\npm-cache\_logs\2017-11-28T04_20_30_160Z-debug.log

**Comment by liangchunn** [comment]
You need to install the latest LTS version of Node.js which is `>=8.x.x`
https://nodejs.org/en/download/
