### ISSUE TITLE
Can't start up, returns error

### ISSUE THREAD

**Issue by Darth4212** [WalshyDev/Discord-Spotify-RPC#28]
Whenever I try to start it I get this 

```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v6.11.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-spotify-rpc@1.1.0~prestart: discord-spotify-rpc@1.1.0
6 silly lifecycle discord-spotify-rpc@1.1.0~prestart: no script for prestart, continuing
7 info lifecycle discord-spotify-rpc@1.1.0~start: discord-spotify-rpc@1.1.0
8 verbose lifecycle discord-spotify-rpc@1.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle discord-spotify-rpc@1.1.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/darth/Documents/Gists/Discord-Spotify-RPC/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle discord-spotify-rpc@1.1.0~start: CWD: /home/darth/Documents/Gists/Discord-Spotify-RPC
11 silly lifecycle discord-spotify-rpc@1.1.0~start: Args: [ '-c', 'node index.js' ]
12 silly lifecycle discord-spotify-rpc@1.1.0~start: Returned: code: 1  signal: null
13 info lifecycle discord-spotify-rpc@1.1.0~start: Failed to exec start script
14 verbose stack Error: discord-spotify-rpc@1.1.0 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid discord-spotify-rpc@1.1.0
16 verbose cwd /home/darth/Documents/Gists/Discord-Spotify-RPC
17 error Linux 4.13.0-19-lowlatency
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.11.4
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error discord-spotify-rpc@1.1.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the discord-spotify-rpc@1.1.0 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the discord-spotify-rpc package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs discord-spotify-rpc
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls discord-spotify-rpc
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by TheOnlyArtz** [comment]
Hey can you please give some more details?
Like: What the command you've tried?

**Comment by Darth4212** [comment]
I have tried the command `npm start` and that is the error it returns
