### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by CasAdair** [WalshyDev/Discord-Spotify-RPC#30]
```
C:\Program Files\nodejs\build\Discord-Spotify-RPC>npm start

> discord-spotify-rpc@1.1.0 start C:\Program Files\nodejs\build\Discord-Spotify-RPC
> node index.js

Starting with clientId 557539301408374784
C:\Program Files\nodejs\build\Discord-Spotify-RPC\index.js:24
                if (res.track.track_resource && res.track.track_resource.name && res.track.track_resource.name != songName) {
                              ^

TypeError: Cannot read property 'track_resource' of undefined
    at C:\Program Files\nodejs\build\Discord-Spotify-RPC\index.js:24:17
    at Request._callback (C:\Program Files\nodejs\build\Discord-Spotify-RPC\node_modules\node-spotify-webhelper\index.js:57:16)
    at Request.self.callback (C:\Program Files\nodejs\build\Discord-Spotify-RPC\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (C:\Program Files\nodejs\build\Discord-Spotify-RPC\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (C:\Program Files\nodejs\build\Discord-Spotify-RPC\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-spotify-rpc@1.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-spotify-rpc@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lady Green Heart\AppData\Roaming\npm-cache\_logs\2019-03-19T12_28_06_250Z-debug.log
```

Terminal is running as an Administrator
Full Log attached below
[2019-03-19T12_28_06_250Z-debug.log](https://github.com/WalshyDev/Discord-Spotify-RPC/files/2983288/2019-03-19T12_28_06_250Z-debug.log)

**Comment by ethanbarclay** [comment]
Run `npm install` or `npm i` in the project directory.

**Comment by CasAdair** [comment]
```npm WARN discord.js@12.0.0-dev requires a peer of bufferutil@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of node-opus@^0.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of opusscript@^0.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of sodium@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of libsodium-wrappers@^0.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of uws@^8.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of zlib-sync@^0.1.0 but none is installed. You must install peer dependencies yourself.

audited 12366 packages in 3.342s
found 0 vulnerabilities```

**Comment by WalshyDev** [comment]
That's fine, just warning of some peer dependencies which aren't needed.

**Comment by CasAdair** [comment]
unfortunately after all this it still responds with the first error @WalshyDev

**Comment by WalshyDev** [comment]
Is Spotify running? @PeashyScript

**Comment by CasAdair** [comment]
yes

**Comment by CasAdair** [comment]
```0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-spotify-rpc@1.1.0~prestart: discord-spotify-rpc@1.1.0
6 info lifecycle discord-spotify-rpc@1.1.0~start: discord-spotify-rpc@1.1.0
7 verbose lifecycle discord-spotify-rpc@1.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle discord-spotify-rpc@1.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Program Files\nodejs\build\Discord-Spotify-RPC\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\PuTTY\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs\;C:\Users\Lady Green Heart\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Nmap;C:\Program Files (x86)\Nmap;C:\Program Files (x86)\FreeArc\bin;C:\Users\Lady Green Heart\AppData\Roaming\npm
9 verbose lifecycle discord-spotify-rpc@1.1.0~start: CWD: C:\Program Files\nodejs\build\Discord-Spotify-RPC
10 silly lifecycle discord-spotify-rpc@1.1.0~start: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle discord-spotify-rpc@1.1.0~start: Returned: code: 1  signal: null
12 info lifecycle discord-spotify-rpc@1.1.0~start: Failed to exec start script
13 verbose stack Error: discord-spotify-rpc@1.1.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid discord-spotify-rpc@1.1.0
15 verbose cwd C:\Program Files\nodejs\build\Discord-Spotify-RPC
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error discord-spotify-rpc@1.1.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the discord-spotify-rpc@1.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by CasAdair** [comment]
Spotify version:
1.0.85.259.g4ab01679
@WalshyDev

**Comment by WalshyDev** [comment]
I don't have the ability to look into this currently, I can try and find some time tonight.
How come you don't use the native Discord implementation? This was maiden before theirs and to satisfy the need for one in the meantime.

**Comment by CasAdair** [comment]
I talk alot while gaming and discord pauses my music.
