### ISSUE TITLE
error at start

### ISSUE THREAD

**Issue by the-mec** [WalshyDev/Discord-Spotify-RPC#9]
PS D:\spotify> npm start

> discord-spotify-rpc@1.1.0 start D:\spotify
> node index.js

(node:11580) ExperimentalWarning: The http2 module is an experimental API.
{ Error: connect ENOENT \\?\pipe\discord-ipc-0
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '\\\\?\\pipe\\discord-ipc-0' }

**Comment by WalshyDev** [comment]
Did you follow this step https://github.com/WalshyDev/Discord-Spotify-RPC#node-spotify-webhelper ?

**Comment by VulgarBear** [comment]
I am also getting a similar error. Followed all the instructions for editing files found in the read me section.

> (node:10544) ExperimentalWarning: The http2 module is an experimental API.
{ Error: connect EPERM \\?\pipe\discord-ipc-0
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
  errno: 'EPERM',
  code: 'EPERM',
  syscall: 'connect',
  address: '\\\\?\\pipe\\discord-ipc-0' }

**Comment by mcao** [comment]
There is no way to resolve this issue for sure right now. However, I have been able to resolve this by:
1. Restarting your Discord client
2. Restarting the program a number of times (3-4 usually)

I'll do a more through investigation and report back later tonight.

**Comment by VulgarBear** [comment]
Okay I'll give that a spin and see what happens

**Comment by SKRUZO** [comment]
I'm getting roughly the same error, and I've ensured I followed all the steps and have the most recent LTS version of Node.JS. 

```
> discord-spotify-rpc@1.1.0 start C:\Users\SKRUZ\Desktop\Discord-Spotify-RPC-master
> node index.js

(node:10724) ExperimentalWarning: The http2 module is an experimental API.
{ Error: connect ENOENT \\?\pipe\discord-ipc-0
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '\\\\?\\pipe\\discord-ipc-0' }
```

I've tried restarting my PC, Discord, restarting the installation process, and so far I can't seem to get it to work.

**Comment by mcao** [comment]
Quite strange. I would recommend joining this server https://discord.gg/bRCvFy9 and asking in the #rpc channel.

**Comment by SKRUZO** [comment]
Okay I don't know if this is what necessarily "fixed" it for me but I switched over to Discord Canary after restarting several more times, and now it's working flawlessly. Could be that some aspect of the RPC and Rich Presence just hasn't made it to live yet, so for now this works. Hopefully this helps anyone else wanting to get a jump start on using Rich Presence.

**Comment by Artuto** [comment]
Im getting this too...
